### ISSUE TITLE
When disconnecting a usb device it throws an exception

### ISSUE THREAD

**Issue by GrantByrne** [GrantByrne/Zapper---Deprecated#13]
```
System.IO.IOException: No such device
   at System.IO.FileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
   at System.IO.FileStream.ReadNative(Span`1 buffer)
   at System.IO.FileStream.ReadSpan(Span`1 destination)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at Zapper.Core.KeyboardMouse.InputReader.Run() in /home/grant/RiderProjects/Zapper/Zapper.Core/KeyboardMouse/InputReader.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

This is likely cause by the fact that the file that the program is reading for input disappears when the user unplugs the usb device

**Comment by GrantByrne** [comment]
These check-ins should have fixed this. Testing need to be done on this.

**Comment by GrantByrne** [comment]
This has been fixed.
