### ISSUE TITLE
Exception is thrown when stopping the bluetooth scanner

### ISSUE THREAD

**Issue by GrantByrne** [GrantByrne/Zapper---Deprecated#38]
Here is the error I got:

```
Tmds.DBus.DBusException: org.bluez.Error.InProgress: Operation already in progress
   at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
   at Tmds.DBus.Connection.CallMethodAsync(Message message)
   at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
   at Zapper.Core.Bluetooth.BluetoothConnection.ScanForDevices() in /home/grant/RiderProjects/Zapper/Zapper.Core/Bluetooth/BluetoothConnection.cs:line 40
```

**Comment by GrantByrne** [comment]
This has been fixed
