### ISSUE TITLE
Exception is thrown sometimes when searching for bluetooth devices

### ISSUE THREAD

**Issue by GrantByrne** [GrantByrne/Zapper---Deprecated#42]
Here is the error that I see.

```
Tmds.DBus.DBusException: org.freedesktop.DBus.Error.UnknownObject: Method "GetAll" with signature "s" on interface "org.freedesktop.DBus.Properties" doesn't exist

   at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
   at Tmds.DBus.Connection.CallMethodAsync(Message message)
   at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
   at Tmds.DBus.CodeGen.DBusObjectProxy.CallNonVoidMethodAsync[T](String iface, String member, Nullable`1 inSignature, MessageWriter writer, ReadMethodDelegate`1 readValue)
   at Zapper.Core.Bluetooth.BluetoothConnection.ScanForDevices() in /home/grant/RiderProjects/Zapper/Zapper.Core/Bluetooth/BluetoothConnection.cs:line 51
```

**Comment by GrantByrne** [comment]
Currently I have this wrapped in a try/catch. At some point I need to go through to understand what specifically is causing this.
